/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface CcAlert {
    /**
     * Show a dismiss (×) button
     * @default false
     */
    dismissible: boolean;
    /**
     * Bold title text displayed above the body
     * @default ''
     */
    heading: string;
    /**
     * Hide the built-in icon
     * @default false
     */
    hideIcon: boolean;
    /**
     * Visual variant
     * @default 'info'
     */
    variant: 'info' | 'success' | 'warning' | 'danger';
  }
  interface CcBadge {
    /**
     * Pill shape (fully rounded) vs subtle rounded corners
     * @default false
     */
    pill: boolean;
    /**
     * Size of the badge
     * @default 'md'
     */
    size: 'sm' | 'md';
    /**
     * Soft tinted style vs solid filled
     * @default true
     */
    soft: boolean;
    /**
     * Visual variant
     * @default 'neutral'
     */
    variant: 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
  }
  interface CcButton {
    /**
     * Disables the button and prevents interaction
     * @default false
     */
    disabled: boolean;
    /**
     * Size of the button
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * HTML button type attribute
     * @default 'button'
     */
    type: 'button' | 'submit' | 'reset';
    /**
     * Visual style of the button
     * @default 'solid'
     */
    variant: 'solid' | 'outline' | 'ghost';
  }
  interface CcInput {
    /**
     * Disables the input
     * @default false
     */
    disabled: boolean;
    /**
     * Error message — also puts the input in an error state
     * @default ''
     */
    error: string;
    /**
     * Helper text displayed below the input
     * @default ''
     */
    hint: string;
    /**
     * Label displayed above the input
     * @default ''
     */
    label: string;
    /**
     * Associates input with a form element id
     * @default ''
     */
    name: string;
    /**
     * Placeholder text
     * @default ''
     */
    placeholder: string;
    /**
     * Makes the input read-only
     * @default false
     */
    readonly: boolean;
    /**
     * Marks the input as required
     * @default false
     */
    required: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * Input type
     * @default 'text'
     */
    type: 'text' | 'email' | 'password' | 'search' | 'url' | 'tel' | 'number';
    /**
     * Bound value
     * @default ''
     */
    value: string;
  }
  interface CcModal {
    /**
     * Heading text displayed in the modal header
     * @default ''
     */
    heading: string;
    /**
     * Closes the modal
     */
    hide: () => Promise<void>;
    /**
     * Hides the close (×) button in the header
     * @default false
     */
    hideClose: boolean;
    /**
     * Controls whether the modal is visible
     * @default false
     */
    open: boolean;
    /**
     * Opens the modal
     */
    show: () => Promise<void>;
    /**
     * Size of the modal dialog
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg' | 'full';
    /**
     * Prevents closing when clicking the backdrop
     * @default false
     */
    staticBackdrop: boolean;
  }
}
export interface CcAlertCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLCcAlertElement;
}
export interface CcInputCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLCcInputElement;
}
export interface CcModalCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLCcModalElement;
}
declare global {
  interface HTMLCcAlertElementEventMap {
    ccDismiss: void;
  }
  interface HTMLCcAlertElement extends Components.CcAlert, HTMLStencilElement {
    addEventListener<K extends keyof HTMLCcAlertElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcAlertElement,
        ev: CcAlertCustomEvent<HTMLCcAlertElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLCcAlertElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcAlertElement,
        ev: CcAlertCustomEvent<HTMLCcAlertElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLCcAlertElement: {
    prototype: HTMLCcAlertElement;
    new (): HTMLCcAlertElement;
  };
  interface HTMLCcBadgeElement extends Components.CcBadge, HTMLStencilElement {}
  var HTMLCcBadgeElement: {
    prototype: HTMLCcBadgeElement;
    new (): HTMLCcBadgeElement;
  };
  interface HTMLCcButtonElement extends Components.CcButton, HTMLStencilElement {}
  var HTMLCcButtonElement: {
    prototype: HTMLCcButtonElement;
    new (): HTMLCcButtonElement;
  };
  interface HTMLCcInputElementEventMap {
    ccInput: string;
    ccBlur: void;
    ccFocus: void;
  }
  interface HTMLCcInputElement extends Components.CcInput, HTMLStencilElement {
    addEventListener<K extends keyof HTMLCcInputElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcInputElement,
        ev: CcInputCustomEvent<HTMLCcInputElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLCcInputElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcInputElement,
        ev: CcInputCustomEvent<HTMLCcInputElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLCcInputElement: {
    prototype: HTMLCcInputElement;
    new (): HTMLCcInputElement;
  };
  interface HTMLCcModalElementEventMap {
    ccClose: void;
  }
  interface HTMLCcModalElement extends Components.CcModal, HTMLStencilElement {
    addEventListener<K extends keyof HTMLCcModalElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcModalElement,
        ev: CcModalCustomEvent<HTMLCcModalElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLCcModalElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcModalElement,
        ev: CcModalCustomEvent<HTMLCcModalElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLCcModalElement: {
    prototype: HTMLCcModalElement;
    new (): HTMLCcModalElement;
  };
  interface HTMLElementTagNameMap {
    'cc-alert': HTMLCcAlertElement;
    'cc-badge': HTMLCcBadgeElement;
    'cc-button': HTMLCcButtonElement;
    'cc-input': HTMLCcInputElement;
    'cc-modal': HTMLCcModalElement;
  }
}
declare namespace LocalJSX {
  interface CcAlert {
    /**
     * Show a dismiss (×) button
     * @default false
     */
    dismissible?: boolean;
    /**
     * Bold title text displayed above the body
     * @default ''
     */
    heading?: string;
    /**
     * Hide the built-in icon
     * @default false
     */
    hideIcon?: boolean;
    /**
     * Emitted when the dismiss button is clicked
     */
    onCcDismiss?: (event: CcAlertCustomEvent<void>) => void;
    /**
     * Visual variant
     * @default 'info'
     */
    variant?: 'info' | 'success' | 'warning' | 'danger';
  }
  interface CcBadge {
    /**
     * Pill shape (fully rounded) vs subtle rounded corners
     * @default false
     */
    pill?: boolean;
    /**
     * Size of the badge
     * @default 'md'
     */
    size?: 'sm' | 'md';
    /**
     * Soft tinted style vs solid filled
     * @default true
     */
    soft?: boolean;
    /**
     * Visual variant
     * @default 'neutral'
     */
    variant?: 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
  }
  interface CcButton {
    /**
     * Disables the button and prevents interaction
     * @default false
     */
    disabled?: boolean;
    /**
     * Size of the button
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
    /**
     * HTML button type attribute
     * @default 'button'
     */
    type?: 'button' | 'submit' | 'reset';
    /**
     * Visual style of the button
     * @default 'solid'
     */
    variant?: 'solid' | 'outline' | 'ghost';
  }
  interface CcInput {
    /**
     * Disables the input
     * @default false
     */
    disabled?: boolean;
    /**
     * Error message — also puts the input in an error state
     * @default ''
     */
    error?: string;
    /**
     * Helper text displayed below the input
     * @default ''
     */
    hint?: string;
    /**
     * Label displayed above the input
     * @default ''
     */
    label?: string;
    /**
     * Associates input with a form element id
     * @default ''
     */
    name?: string;
    /**
     * Emitted when the input loses focus
     */
    onCcBlur?: (event: CcInputCustomEvent<void>) => void;
    /**
     * Emitted when the input gains focus
     */
    onCcFocus?: (event: CcInputCustomEvent<void>) => void;
    /**
     * Emitted on every input event with the current value
     */
    onCcInput?: (event: CcInputCustomEvent<string>) => void;
    /**
     * Placeholder text
     * @default ''
     */
    placeholder?: string;
    /**
     * Makes the input read-only
     * @default false
     */
    readonly?: boolean;
    /**
     * Marks the input as required
     * @default false
     */
    required?: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
    /**
     * Input type
     * @default 'text'
     */
    type?: 'text' | 'email' | 'password' | 'search' | 'url' | 'tel' | 'number';
    /**
     * Bound value
     * @default ''
     */
    value?: string;
  }
  interface CcModal {
    /**
     * Heading text displayed in the modal header
     * @default ''
     */
    heading?: string;
    /**
     * Hides the close (×) button in the header
     * @default false
     */
    hideClose?: boolean;
    /**
     * Emitted when the modal requests to be closed
     */
    onCcClose?: (event: CcModalCustomEvent<void>) => void;
    /**
     * Controls whether the modal is visible
     * @default false
     */
    open?: boolean;
    /**
     * Size of the modal dialog
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg' | 'full';
    /**
     * Prevents closing when clicking the backdrop
     * @default false
     */
    staticBackdrop?: boolean;
  }

  interface CcBadgeAttributes {
    variant: 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
    size: 'sm' | 'md';
    pill: boolean;
    soft: boolean;
  }
  interface CcAlertAttributes {
    variant: 'info' | 'success' | 'warning' | 'danger';
    heading: string;
    dismissible: boolean;
    hideIcon: boolean;
  }
  interface CcButtonAttributes {
    variant: 'solid' | 'outline' | 'ghost';
    size: 'sm' | 'md' | 'lg';
    disabled: boolean;
    type: 'button' | 'submit' | 'reset';
  }
  interface CcInputAttributes {
    type: 'text' | 'email' | 'password' | 'search' | 'url' | 'tel' | 'number';
    value: string;
    placeholder: string;
    label: string;
    hint: string;
    error: string;
    size: 'sm' | 'md' | 'lg';
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    name: string;
  }
  interface CcModalAttributes {
    open: boolean;
    heading: string;
    size: 'sm' | 'md' | 'lg' | 'full';
    hideClose: boolean;
    staticBackdrop: boolean;
  }

  interface IntrinsicElements {
    'cc-alert': Omit<CcAlert, keyof CcAlertAttributes> & {
      [K in keyof CcAlert & keyof CcAlertAttributes]?: CcAlert[K];
    } & { [K in keyof CcAlert & keyof CcAlertAttributes as `attr:${K}`]?: CcAlertAttributes[K] } & {
      [K in keyof CcAlert & keyof CcAlertAttributes as `prop:${K}`]?: CcAlert[K];
    };
    'cc-badge': Omit<CcBadge, keyof CcBadgeAttributes> & {
      [K in keyof CcBadge & keyof CcBadgeAttributes]?: CcBadge[K];
    } & { [K in keyof CcBadge & keyof CcBadgeAttributes as `attr:${K}`]?: CcBadgeAttributes[K] } & {
      [K in keyof CcBadge & keyof CcBadgeAttributes as `prop:${K}`]?: CcBadge[K];
    };
    'cc-button': Omit<CcButton, keyof CcButtonAttributes> & {
      [K in keyof CcButton & keyof CcButtonAttributes]?: CcButton[K];
    } & {
      [K in keyof CcButton & keyof CcButtonAttributes as `attr:${K}`]?: CcButtonAttributes[K];
    } & { [K in keyof CcButton & keyof CcButtonAttributes as `prop:${K}`]?: CcButton[K] };
    'cc-input': Omit<CcInput, keyof CcInputAttributes> & {
      [K in keyof CcInput & keyof CcInputAttributes]?: CcInput[K];
    } & { [K in keyof CcInput & keyof CcInputAttributes as `attr:${K}`]?: CcInputAttributes[K] } & {
      [K in keyof CcInput & keyof CcInputAttributes as `prop:${K}`]?: CcInput[K];
    };
    'cc-modal': Omit<CcModal, keyof CcModalAttributes> & {
      [K in keyof CcModal & keyof CcModalAttributes]?: CcModal[K];
    } & { [K in keyof CcModal & keyof CcModalAttributes as `attr:${K}`]?: CcModalAttributes[K] } & {
      [K in keyof CcModal & keyof CcModalAttributes as `prop:${K}`]?: CcModal[K];
    };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'cc-alert': LocalJSX.IntrinsicElements['cc-alert'] &
        JSXBase.HTMLAttributes<HTMLCcAlertElement>;
      'cc-badge': LocalJSX.IntrinsicElements['cc-badge'] &
        JSXBase.HTMLAttributes<HTMLCcBadgeElement>;
      'cc-button': LocalJSX.IntrinsicElements['cc-button'] &
        JSXBase.HTMLAttributes<HTMLCcButtonElement>;
      'cc-input': LocalJSX.IntrinsicElements['cc-input'] &
        JSXBase.HTMLAttributes<HTMLCcInputElement>;
      'cc-modal': LocalJSX.IntrinsicElements['cc-modal'] &
        JSXBase.HTMLAttributes<HTMLCcModalElement>;
    }
  }
}
