/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface CcButton {
    /**
     * Disables the button and prevents interaction
     * @default false
     */
    disabled: boolean;
    /**
     * Size of the button
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * HTML button type attribute
     * @default 'button'
     */
    type: 'button' | 'submit' | 'reset';
    /**
     * Visual style of the button
     * @default 'solid'
     */
    variant: 'solid' | 'outline' | 'ghost';
  }
}
declare global {
  interface HTMLCcButtonElement extends Components.CcButton, HTMLStencilElement {}
  var HTMLCcButtonElement: {
    prototype: HTMLCcButtonElement;
    new (): HTMLCcButtonElement;
  };
  interface HTMLElementTagNameMap {
    'cc-button': HTMLCcButtonElement;
  }
}
declare namespace LocalJSX {
  interface CcButton {
    /**
     * Disables the button and prevents interaction
     * @default false
     */
    disabled?: boolean;
    /**
     * Size of the button
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
    /**
     * HTML button type attribute
     * @default 'button'
     */
    type?: 'button' | 'submit' | 'reset';
    /**
     * Visual style of the button
     * @default 'solid'
     */
    variant?: 'solid' | 'outline' | 'ghost';
  }

  interface CcButtonAttributes {
    variant: 'solid' | 'outline' | 'ghost';
    size: 'sm' | 'md' | 'lg';
    disabled: boolean;
    type: 'button' | 'submit' | 'reset';
  }

  interface IntrinsicElements {
    'cc-button': Omit<CcButton, keyof CcButtonAttributes> & {
      [K in keyof CcButton & keyof CcButtonAttributes]?: CcButton[K];
    } & {
      [K in keyof CcButton & keyof CcButtonAttributes as `attr:${K}`]?: CcButtonAttributes[K];
    } & { [K in keyof CcButton & keyof CcButtonAttributes as `prop:${K}`]?: CcButton[K] };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'cc-button': LocalJSX.IntrinsicElements['cc-button'] &
        JSXBase.HTMLAttributes<HTMLCcButtonElement>;
    }
  }
}
