/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface CcButton {
    /**
     * Disables the button and prevents interaction
     * @default false
     */
    disabled: boolean;
    /**
     * Size of the button
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * HTML button type attribute
     * @default 'button'
     */
    type: 'button' | 'submit' | 'reset';
    /**
     * Visual style of the button
     * @default 'solid'
     */
    variant: 'solid' | 'outline' | 'ghost';
  }
  interface CcInput {
    /**
     * Disables the input
     * @default false
     */
    disabled: boolean;
    /**
     * Error message — also puts the input in an error state
     * @default ''
     */
    error: string;
    /**
     * Helper text displayed below the input
     * @default ''
     */
    hint: string;
    /**
     * Label displayed above the input
     * @default ''
     */
    label: string;
    /**
     * Associates input with a form element id
     * @default ''
     */
    name: string;
    /**
     * Placeholder text
     * @default ''
     */
    placeholder: string;
    /**
     * Makes the input read-only
     * @default false
     */
    readonly: boolean;
    /**
     * Marks the input as required
     * @default false
     */
    required: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * Input type
     * @default 'text'
     */
    type: 'text' | 'email' | 'password' | 'search' | 'url' | 'tel' | 'number';
    /**
     * Bound value
     * @default ''
     */
    value: string;
  }
  interface CcSelect {
    /**
     * Disables the select
     * @default false
     */
    disabled: boolean;
    /**
     * Error message — also puts the select in an error state
     * @default ''
     */
    error: string;
    /**
     * Helper text displayed below the select
     * @default ''
     */
    hint: string;
    /**
     * Label displayed above the select
     * @default ''
     */
    label: string;
    /**
     * Associates select with a form element id
     * @default ''
     */
    name: string;
    /**
     * Placeholder option shown when no value is selected
     * @default ''
     */
    placeholder: string;
    /**
     * Marks the select as required
     * @default false
     */
    required: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * Bound value — must match one of the option values
     * @default ''
     */
    value: string;
  }
}
export interface CcInputCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLCcInputElement;
}
export interface CcSelectCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLCcSelectElement;
}
declare global {
  interface HTMLCcButtonElement extends Components.CcButton, HTMLStencilElement {}
  var HTMLCcButtonElement: {
    prototype: HTMLCcButtonElement;
    new (): HTMLCcButtonElement;
  };
  interface HTMLCcInputElementEventMap {
    ccInput: string;
    ccBlur: void;
    ccFocus: void;
  }
  interface HTMLCcInputElement extends Components.CcInput, HTMLStencilElement {
    addEventListener<K extends keyof HTMLCcInputElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcInputElement,
        ev: CcInputCustomEvent<HTMLCcInputElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLCcInputElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcInputElement,
        ev: CcInputCustomEvent<HTMLCcInputElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLCcInputElement: {
    prototype: HTMLCcInputElement;
    new (): HTMLCcInputElement;
  };
  interface HTMLCcSelectElementEventMap {
    ccChange: string;
    ccBlur: void;
    ccFocus: void;
  }
  interface HTMLCcSelectElement extends Components.CcSelect, HTMLStencilElement {
    addEventListener<K extends keyof HTMLCcSelectElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcSelectElement,
        ev: CcSelectCustomEvent<HTMLCcSelectElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLCcSelectElementEventMap>(
      type: K,
      listener: (
        this: HTMLCcSelectElement,
        ev: CcSelectCustomEvent<HTMLCcSelectElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLCcSelectElement: {
    prototype: HTMLCcSelectElement;
    new (): HTMLCcSelectElement;
  };
  interface HTMLElementTagNameMap {
    'cc-button': HTMLCcButtonElement;
    'cc-input': HTMLCcInputElement;
    'cc-select': HTMLCcSelectElement;
  }
}
declare namespace LocalJSX {
  interface CcButton {
    /**
     * Disables the button and prevents interaction
     * @default false
     */
    disabled?: boolean;
    /**
     * Size of the button
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
    /**
     * HTML button type attribute
     * @default 'button'
     */
    type?: 'button' | 'submit' | 'reset';
    /**
     * Visual style of the button
     * @default 'solid'
     */
    variant?: 'solid' | 'outline' | 'ghost';
  }
  interface CcInput {
    /**
     * Disables the input
     * @default false
     */
    disabled?: boolean;
    /**
     * Error message — also puts the input in an error state
     * @default ''
     */
    error?: string;
    /**
     * Helper text displayed below the input
     * @default ''
     */
    hint?: string;
    /**
     * Label displayed above the input
     * @default ''
     */
    label?: string;
    /**
     * Associates input with a form element id
     * @default ''
     */
    name?: string;
    /**
     * Emitted when the input loses focus
     */
    onCcBlur?: (event: CcInputCustomEvent<void>) => void;
    /**
     * Emitted when the input gains focus
     */
    onCcFocus?: (event: CcInputCustomEvent<void>) => void;
    /**
     * Emitted on every input event with the current value
     */
    onCcInput?: (event: CcInputCustomEvent<string>) => void;
    /**
     * Placeholder text
     * @default ''
     */
    placeholder?: string;
    /**
     * Makes the input read-only
     * @default false
     */
    readonly?: boolean;
    /**
     * Marks the input as required
     * @default false
     */
    required?: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
    /**
     * Input type
     * @default 'text'
     */
    type?: 'text' | 'email' | 'password' | 'search' | 'url' | 'tel' | 'number';
    /**
     * Bound value
     * @default ''
     */
    value?: string;
  }
  interface CcSelect {
    /**
     * Disables the select
     * @default false
     */
    disabled?: boolean;
    /**
     * Error message — also puts the select in an error state
     * @default ''
     */
    error?: string;
    /**
     * Helper text displayed below the select
     * @default ''
     */
    hint?: string;
    /**
     * Label displayed above the select
     * @default ''
     */
    label?: string;
    /**
     * Associates select with a form element id
     * @default ''
     */
    name?: string;
    /**
     * Emitted when the select loses focus
     */
    onCcBlur?: (event: CcSelectCustomEvent<void>) => void;
    /**
     * Emitted when the selected value changes
     */
    onCcChange?: (event: CcSelectCustomEvent<string>) => void;
    /**
     * Emitted when the select gains focus
     */
    onCcFocus?: (event: CcSelectCustomEvent<void>) => void;
    /**
     * Placeholder option shown when no value is selected
     * @default ''
     */
    placeholder?: string;
    /**
     * Marks the select as required
     * @default false
     */
    required?: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
    /**
     * Bound value — must match one of the option values
     * @default ''
     */
    value?: string;
  }

  interface CcButtonAttributes {
    variant: 'solid' | 'outline' | 'ghost';
    size: 'sm' | 'md' | 'lg';
    disabled: boolean;
    type: 'button' | 'submit' | 'reset';
  }
  interface CcInputAttributes {
    type: 'text' | 'email' | 'password' | 'search' | 'url' | 'tel' | 'number';
    value: string;
    placeholder: string;
    label: string;
    hint: string;
    error: string;
    size: 'sm' | 'md' | 'lg';
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    name: string;
  }
  interface CcSelectAttributes {
    value: string;
    label: string;
    placeholder: string;
    hint: string;
    error: string;
    size: 'sm' | 'md' | 'lg';
    disabled: boolean;
    required: boolean;
    name: string;
  }

  interface IntrinsicElements {
    'cc-button': Omit<CcButton, keyof CcButtonAttributes> & {
      [K in keyof CcButton & keyof CcButtonAttributes]?: CcButton[K];
    } & {
      [K in keyof CcButton & keyof CcButtonAttributes as `attr:${K}`]?: CcButtonAttributes[K];
    } & { [K in keyof CcButton & keyof CcButtonAttributes as `prop:${K}`]?: CcButton[K] };
    'cc-input': Omit<CcInput, keyof CcInputAttributes> & {
      [K in keyof CcInput & keyof CcInputAttributes]?: CcInput[K];
    } & { [K in keyof CcInput & keyof CcInputAttributes as `attr:${K}`]?: CcInputAttributes[K] } & {
      [K in keyof CcInput & keyof CcInputAttributes as `prop:${K}`]?: CcInput[K];
    };
    'cc-select': Omit<CcSelect, keyof CcSelectAttributes> & {
      [K in keyof CcSelect & keyof CcSelectAttributes]?: CcSelect[K];
    } & {
      [K in keyof CcSelect & keyof CcSelectAttributes as `attr:${K}`]?: CcSelectAttributes[K];
    } & { [K in keyof CcSelect & keyof CcSelectAttributes as `prop:${K}`]?: CcSelect[K] };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'cc-button': LocalJSX.IntrinsicElements['cc-button'] &
        JSXBase.HTMLAttributes<HTMLCcButtonElement>;
      'cc-input': LocalJSX.IntrinsicElements['cc-input'] &
        JSXBase.HTMLAttributes<HTMLCcInputElement>;
      'cc-select': LocalJSX.IntrinsicElements['cc-select'] &
        JSXBase.HTMLAttributes<HTMLCcSelectElement>;
    }
  }
}
